# Install script for directory: /users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/Elements/Colorizer

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Debug")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Data/")
  IF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
  IF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
FILE(INSTALL DESTINATION "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Data" TYPE DIRECTORY FILES "/users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/Elements/Colorizer/data/" REGEX "/[^/]*\\.svn$" EXCLUDE REGEX "/[^/]*\\.qrc$" EXCLUDE REGEX "/[^/]*\\.ts$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Resource/")
  IF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
  IF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
FILE(INSTALL DESTINATION "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Resource" TYPE DIRECTORY FILES "/users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/Elements/Colorizer/resource/" REGEX "/[^/]*\\.svn$" EXCLUDE REGEX "/[^/]*\\.qrc$" EXCLUDE REGEX "/[^/]*\\.ts$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Documentation/")
  IF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
  IF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  ENDIF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
FILE(INSTALL DESTINATION "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Documentation" TYPE DIRECTORY FILES "/users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/Elements/Colorizer/doc/" REGEX "/[^/]*\\.svn$" EXCLUDE REGEX "/[^/]*\\.qrc$" EXCLUDE REGEX "/[^/]*\\.ts$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  IF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    IF(EXISTS "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      FILE(RPATH_CHECK
           FILE "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so"
           RPATH "")
    ENDIF()
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
    IF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    ENDIF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    IF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    ENDIF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
FILE(INSTALL DESTINATION "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug" TYPE SHARED_LIBRARY FILES "/users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/build-Elements-Desktop_Qt_5_9_3_GCC_64bit-Default/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
    IF(EXISTS "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      FILE(RPATH_REMOVE
           FILE "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      IF(CMAKE_INSTALL_DO_STRIP)
        EXECUTE_PROCESS(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      ENDIF(CMAKE_INSTALL_DO_STRIP)
    ENDIF()
  ENDIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  IF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    IF(EXISTS "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      FILE(RPATH_CHECK
           FILE "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so"
           RPATH "")
    ENDIF()
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
    IF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    ENDIF (CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    IF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    ENDIF (CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
FILE(INSTALL DESTINATION "/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233" TYPE SHARED_LIBRARY FILES "/users/misc-b/INF473/johanna.jussey/Projets/INF473-x16/build-Elements-Desktop_Qt_5_9_3_GCC_64bit-Default/Debug/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
    IF(EXISTS "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      FILE(RPATH_REMOVE
           FILE "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      IF(CMAKE_INSTALL_DO_STRIP)
        EXECUTE_PROCESS(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}/users/eleves-a/2016/johanna.jussey/.NANO-D/SAMSON/DEVELOPER/Elements/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233/E770E4DE-F2C4-A42B-8BE1-3EBEE8BC9233.so")
      ENDIF(CMAKE_INSTALL_DO_STRIP)
    ENDIF()
  ENDIF("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

